spring.application.name=movies-api

# SQLite datasource
spring.datasource.url=jdbc:sqlite:movies.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Hibernate Dialect for SQLite
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# Automatically create/update tables based on entities
spring.jpa.hibernate.ddl-auto=update

# Show SQL queries in console (optional, useful for debugging)
spring.jpa.show-sql=true
